/**
 * SendPost API
 * Email API and SMTP relay to not just send and measure email sending, but also alert and optimise. We provide you with tools, expertise and support needed to reliably deliver emails to your customers inboxes on time, every time.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: hello@sendpost.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import City from './City';
import Device from './Device';
import Os from './Os';
import UserAgent from './UserAgent';

/**
 * The EventMetadata model module.
 * @module sendpost/model/EventMetadata
 * @version 1.0.0
 */
class EventMetadata {
    /**
     * Constructs a new <code>EventMetadata</code>.
     * @alias module:sendpost/model/EventMetadata
     */
    constructor() { 
        
        EventMetadata.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>EventMetadata</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:sendpost/model/EventMetadata} obj Optional instance to populate.
     * @return {module:sendpost/model/EventMetadata} The populated <code>EventMetadata</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new EventMetadata();

            if (data.hasOwnProperty('clickedURL')) {
                obj['clickedURL'] = ApiClient.convertToType(data['clickedURL'], 'String');
            }
            if (data.hasOwnProperty('device')) {
                obj['device'] = Device.constructFromObject(data['device']);
            }
            if (data.hasOwnProperty('geo')) {
                obj['geo'] = City.constructFromObject(data['geo']);
            }
            if (data.hasOwnProperty('os')) {
                obj['os'] = Os.constructFromObject(data['os']);
            }
            if (data.hasOwnProperty('smtpCode')) {
                obj['smtpCode'] = ApiClient.convertToType(data['smtpCode'], 'Number');
            }
            if (data.hasOwnProperty('smtpDescription')) {
                obj['smtpDescription'] = ApiClient.convertToType(data['smtpDescription'], 'String');
            }
            if (data.hasOwnProperty('userAgent')) {
                obj['userAgent'] = UserAgent.constructFromObject(data['userAgent']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>EventMetadata</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>EventMetadata</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['clickedURL'] && !(typeof data['clickedURL'] === 'string' || data['clickedURL'] instanceof String)) {
            throw new Error("Expected the field `clickedURL` to be a primitive type in the JSON string but got " + data['clickedURL']);
        }
        // validate the optional field `device`
        if (data['device']) { // data not null
          Device.validateJSON(data['device']);
        }
        // validate the optional field `geo`
        if (data['geo']) { // data not null
          City.validateJSON(data['geo']);
        }
        // validate the optional field `os`
        if (data['os']) { // data not null
          Os.validateJSON(data['os']);
        }
        // ensure the json data is a string
        if (data['smtpDescription'] && !(typeof data['smtpDescription'] === 'string' || data['smtpDescription'] instanceof String)) {
            throw new Error("Expected the field `smtpDescription` to be a primitive type in the JSON string but got " + data['smtpDescription']);
        }
        // validate the optional field `userAgent`
        if (data['userAgent']) { // data not null
          UserAgent.validateJSON(data['userAgent']);
        }

        return true;
    }

/**
     * @return {String}
     */
    getClickedURL() {
        return this.clickedURL;
    }

    /**
     * @param {String} clickedURL
     */
    setClickedURL(clickedURL) {
        this['clickedURL'] = clickedURL;
    }
/**
     * @return {module:sendpost/model/Device}
     */
    getDevice() {
        return this.device;
    }

    /**
     * @param {module:sendpost/model/Device} device
     */
    setDevice(device) {
        this['device'] = device;
    }
/**
     * @return {module:sendpost/model/City}
     */
    getGeo() {
        return this.geo;
    }

    /**
     * @param {module:sendpost/model/City} geo
     */
    setGeo(geo) {
        this['geo'] = geo;
    }
/**
     * @return {module:sendpost/model/Os}
     */
    getOs() {
        return this.os;
    }

    /**
     * @param {module:sendpost/model/Os} os
     */
    setOs(os) {
        this['os'] = os;
    }
/**
     * @return {Number}
     */
    getSmtpCode() {
        return this.smtpCode;
    }

    /**
     * @param {Number} smtpCode
     */
    setSmtpCode(smtpCode) {
        this['smtpCode'] = smtpCode;
    }
/**
     * @return {String}
     */
    getSmtpDescription() {
        return this.smtpDescription;
    }

    /**
     * @param {String} smtpDescription
     */
    setSmtpDescription(smtpDescription) {
        this['smtpDescription'] = smtpDescription;
    }
/**
     * @return {module:sendpost/model/UserAgent}
     */
    getUserAgent() {
        return this.userAgent;
    }

    /**
     * @param {module:sendpost/model/UserAgent} userAgent
     */
    setUserAgent(userAgent) {
        this['userAgent'] = userAgent;
    }

}



/**
 * @member {String} clickedURL
 */
EventMetadata.prototype['clickedURL'] = undefined;

/**
 * @member {module:sendpost/model/Device} device
 */
EventMetadata.prototype['device'] = undefined;

/**
 * @member {module:sendpost/model/City} geo
 */
EventMetadata.prototype['geo'] = undefined;

/**
 * @member {module:sendpost/model/Os} os
 */
EventMetadata.prototype['os'] = undefined;

/**
 * @member {Number} smtpCode
 */
EventMetadata.prototype['smtpCode'] = undefined;

/**
 * @member {String} smtpDescription
 */
EventMetadata.prototype['smtpDescription'] = undefined;

/**
 * @member {module:sendpost/model/UserAgent} userAgent
 */
EventMetadata.prototype['userAgent'] = undefined;






export default EventMetadata;

