/**
 * SendPost API
 * Email API and SMTP relay to not just send and measure email sending, but also alert and optimise. We provide you with tools, expertise and support needed to reliably deliver emails to your customers inboxes on time, every time.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: hello@sendpost.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Attachment from './Attachment';
import CopyTo from './CopyTo';
import From from './From';
import ReplyTo from './ReplyTo';
import To from './To';

/**
 * The QEmailMessage model module.
 * @module sendpost/model/QEmailMessage
 * @version 1.0.0
 */
class QEmailMessage {
    /**
     * Constructs a new <code>QEmailMessage</code>.
     * @alias module:sendpost/model/QEmailMessage
     */
    constructor() { 
        
        QEmailMessage.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>QEmailMessage</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:sendpost/model/QEmailMessage} obj Optional instance to populate.
     * @return {module:sendpost/model/QEmailMessage} The populated <code>QEmailMessage</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new QEmailMessage();

            if (data.hasOwnProperty('accountID')) {
                obj['accountID'] = ApiClient.convertToType(data['accountID'], 'Number');
            }
            if (data.hasOwnProperty('ampBody')) {
                obj['ampBody'] = ApiClient.convertToType(data['ampBody'], 'String');
            }
            if (data.hasOwnProperty('attachments')) {
                obj['attachments'] = ApiClient.convertToType(data['attachments'], [Attachment]);
            }
            if (data.hasOwnProperty('attempt')) {
                obj['attempt'] = ApiClient.convertToType(data['attempt'], 'Number');
            }
            if (data.hasOwnProperty('customFields')) {
                obj['customFields'] = ApiClient.convertToType(data['customFields'], Object);
            }
            if (data.hasOwnProperty('emailType')) {
                obj['emailType'] = ApiClient.convertToType(data['emailType'], 'String');
            }
            if (data.hasOwnProperty('from')) {
                obj['from'] = From.constructFromObject(data['from']);
            }
            if (data.hasOwnProperty('groups')) {
                obj['groups'] = ApiClient.convertToType(data['groups'], ['String']);
            }
            if (data.hasOwnProperty('headerBcc')) {
                obj['headerBcc'] = ApiClient.convertToType(data['headerBcc'], [CopyTo]);
            }
            if (data.hasOwnProperty('headerCc')) {
                obj['headerCc'] = ApiClient.convertToType(data['headerCc'], [CopyTo]);
            }
            if (data.hasOwnProperty('headerTo')) {
                obj['headerTo'] = To.constructFromObject(data['headerTo']);
            }
            if (data.hasOwnProperty('headers')) {
                obj['headers'] = ApiClient.convertToType(data['headers'], Object);
            }
            if (data.hasOwnProperty('htmlBody')) {
                obj['htmlBody'] = ApiClient.convertToType(data['htmlBody'], 'String');
            }
            if (data.hasOwnProperty('ipID')) {
                obj['ipID'] = ApiClient.convertToType(data['ipID'], 'Number');
            }
            if (data.hasOwnProperty('ipPool')) {
                obj['ipPool'] = ApiClient.convertToType(data['ipPool'], 'String');
            }
            if (data.hasOwnProperty('localIP')) {
                obj['localIP'] = ApiClient.convertToType(data['localIP'], 'String');
            }
            if (data.hasOwnProperty('messageID')) {
                obj['messageID'] = ApiClient.convertToType(data['messageID'], 'String');
            }
            if (data.hasOwnProperty('preText')) {
                obj['preText'] = ApiClient.convertToType(data['preText'], 'String');
            }
            if (data.hasOwnProperty('publicIP')) {
                obj['publicIP'] = ApiClient.convertToType(data['publicIP'], 'String');
            }
            if (data.hasOwnProperty('replyTo')) {
                obj['replyTo'] = ReplyTo.constructFromObject(data['replyTo']);
            }
            if (data.hasOwnProperty('subAccountID')) {
                obj['subAccountID'] = ApiClient.convertToType(data['subAccountID'], 'Number');
            }
            if (data.hasOwnProperty('subject')) {
                obj['subject'] = ApiClient.convertToType(data['subject'], 'String');
            }
            if (data.hasOwnProperty('submittedAt')) {
                obj['submittedAt'] = ApiClient.convertToType(data['submittedAt'], 'Number');
            }
            if (data.hasOwnProperty('textBody')) {
                obj['textBody'] = ApiClient.convertToType(data['textBody'], 'String');
            }
            if (data.hasOwnProperty('to')) {
                obj['to'] = To.constructFromObject(data['to']);
            }
            if (data.hasOwnProperty('trackClicks')) {
                obj['trackClicks'] = ApiClient.convertToType(data['trackClicks'], 'Boolean');
            }
            if (data.hasOwnProperty('trackOpens')) {
                obj['trackOpens'] = ApiClient.convertToType(data['trackOpens'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>QEmailMessage</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>QEmailMessage</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['ampBody'] && !(typeof data['ampBody'] === 'string' || data['ampBody'] instanceof String)) {
            throw new Error("Expected the field `ampBody` to be a primitive type in the JSON string but got " + data['ampBody']);
        }
        if (data['attachments']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['attachments'])) {
                throw new Error("Expected the field `attachments` to be an array in the JSON data but got " + data['attachments']);
            }
            // validate the optional field `attachments` (array)
            for (const item of data['attachments']) {
                Attachment.validateJSON(item);
            };
        }
        // ensure the json data is a string
        if (data['emailType'] && !(typeof data['emailType'] === 'string' || data['emailType'] instanceof String)) {
            throw new Error("Expected the field `emailType` to be a primitive type in the JSON string but got " + data['emailType']);
        }
        // validate the optional field `from`
        if (data['from']) { // data not null
          From.validateJSON(data['from']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['groups'])) {
            throw new Error("Expected the field `groups` to be an array in the JSON data but got " + data['groups']);
        }
        if (data['headerBcc']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['headerBcc'])) {
                throw new Error("Expected the field `headerBcc` to be an array in the JSON data but got " + data['headerBcc']);
            }
            // validate the optional field `headerBcc` (array)
            for (const item of data['headerBcc']) {
                CopyTo.validateJSON(item);
            };
        }
        if (data['headerCc']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['headerCc'])) {
                throw new Error("Expected the field `headerCc` to be an array in the JSON data but got " + data['headerCc']);
            }
            // validate the optional field `headerCc` (array)
            for (const item of data['headerCc']) {
                CopyTo.validateJSON(item);
            };
        }
        // validate the optional field `headerTo`
        if (data['headerTo']) { // data not null
          To.validateJSON(data['headerTo']);
        }
        // ensure the json data is a string
        if (data['htmlBody'] && !(typeof data['htmlBody'] === 'string' || data['htmlBody'] instanceof String)) {
            throw new Error("Expected the field `htmlBody` to be a primitive type in the JSON string but got " + data['htmlBody']);
        }
        // ensure the json data is a string
        if (data['ipPool'] && !(typeof data['ipPool'] === 'string' || data['ipPool'] instanceof String)) {
            throw new Error("Expected the field `ipPool` to be a primitive type in the JSON string but got " + data['ipPool']);
        }
        // ensure the json data is a string
        if (data['localIP'] && !(typeof data['localIP'] === 'string' || data['localIP'] instanceof String)) {
            throw new Error("Expected the field `localIP` to be a primitive type in the JSON string but got " + data['localIP']);
        }
        // ensure the json data is a string
        if (data['messageID'] && !(typeof data['messageID'] === 'string' || data['messageID'] instanceof String)) {
            throw new Error("Expected the field `messageID` to be a primitive type in the JSON string but got " + data['messageID']);
        }
        // ensure the json data is a string
        if (data['preText'] && !(typeof data['preText'] === 'string' || data['preText'] instanceof String)) {
            throw new Error("Expected the field `preText` to be a primitive type in the JSON string but got " + data['preText']);
        }
        // ensure the json data is a string
        if (data['publicIP'] && !(typeof data['publicIP'] === 'string' || data['publicIP'] instanceof String)) {
            throw new Error("Expected the field `publicIP` to be a primitive type in the JSON string but got " + data['publicIP']);
        }
        // validate the optional field `replyTo`
        if (data['replyTo']) { // data not null
          ReplyTo.validateJSON(data['replyTo']);
        }
        // ensure the json data is a string
        if (data['subject'] && !(typeof data['subject'] === 'string' || data['subject'] instanceof String)) {
            throw new Error("Expected the field `subject` to be a primitive type in the JSON string but got " + data['subject']);
        }
        // ensure the json data is a string
        if (data['textBody'] && !(typeof data['textBody'] === 'string' || data['textBody'] instanceof String)) {
            throw new Error("Expected the field `textBody` to be a primitive type in the JSON string but got " + data['textBody']);
        }
        // validate the optional field `to`
        if (data['to']) { // data not null
          To.validateJSON(data['to']);
        }

        return true;
    }

/**
     * @return {Number}
     */
    getAccountID() {
        return this.accountID;
    }

    /**
     * @param {Number} accountID
     */
    setAccountID(accountID) {
        this['accountID'] = accountID;
    }
/**
     * @return {String}
     */
    getAmpBody() {
        return this.ampBody;
    }

    /**
     * @param {String} ampBody
     */
    setAmpBody(ampBody) {
        this['ampBody'] = ampBody;
    }
/**
     * @return {Array.<module:sendpost/model/Attachment>}
     */
    getAttachments() {
        return this.attachments;
    }

    /**
     * @param {Array.<module:sendpost/model/Attachment>} attachments
     */
    setAttachments(attachments) {
        this['attachments'] = attachments;
    }
/**
     * @return {Number}
     */
    getAttempt() {
        return this.attempt;
    }

    /**
     * @param {Number} attempt
     */
    setAttempt(attempt) {
        this['attempt'] = attempt;
    }
/**
     * @return {Object}
     */
    getCustomFields() {
        return this.customFields;
    }

    /**
     * @param {Object} customFields
     */
    setCustomFields(customFields) {
        this['customFields'] = customFields;
    }
/**
     * @return {String}
     */
    getEmailType() {
        return this.emailType;
    }

    /**
     * @param {String} emailType
     */
    setEmailType(emailType) {
        this['emailType'] = emailType;
    }
/**
     * @return {module:sendpost/model/From}
     */
    getFrom() {
        return this.from;
    }

    /**
     * @param {module:sendpost/model/From} from
     */
    setFrom(from) {
        this['from'] = from;
    }
/**
     * @return {Array.<String>}
     */
    getGroups() {
        return this.groups;
    }

    /**
     * @param {Array.<String>} groups
     */
    setGroups(groups) {
        this['groups'] = groups;
    }
/**
     * @return {Array.<module:sendpost/model/CopyTo>}
     */
    getHeaderBcc() {
        return this.headerBcc;
    }

    /**
     * @param {Array.<module:sendpost/model/CopyTo>} headerBcc
     */
    setHeaderBcc(headerBcc) {
        this['headerBcc'] = headerBcc;
    }
/**
     * @return {Array.<module:sendpost/model/CopyTo>}
     */
    getHeaderCc() {
        return this.headerCc;
    }

    /**
     * @param {Array.<module:sendpost/model/CopyTo>} headerCc
     */
    setHeaderCc(headerCc) {
        this['headerCc'] = headerCc;
    }
/**
     * @return {module:sendpost/model/To}
     */
    getHeaderTo() {
        return this.headerTo;
    }

    /**
     * @param {module:sendpost/model/To} headerTo
     */
    setHeaderTo(headerTo) {
        this['headerTo'] = headerTo;
    }
/**
     * @return {Object}
     */
    getHeaders() {
        return this.headers;
    }

    /**
     * @param {Object} headers
     */
    setHeaders(headers) {
        this['headers'] = headers;
    }
/**
     * @return {String}
     */
    getHtmlBody() {
        return this.htmlBody;
    }

    /**
     * @param {String} htmlBody
     */
    setHtmlBody(htmlBody) {
        this['htmlBody'] = htmlBody;
    }
/**
     * @return {Number}
     */
    getIpID() {
        return this.ipID;
    }

    /**
     * @param {Number} ipID
     */
    setIpID(ipID) {
        this['ipID'] = ipID;
    }
/**
     * @return {String}
     */
    getIpPool() {
        return this.ipPool;
    }

    /**
     * @param {String} ipPool
     */
    setIpPool(ipPool) {
        this['ipPool'] = ipPool;
    }
/**
     * @return {String}
     */
    getLocalIP() {
        return this.localIP;
    }

    /**
     * @param {String} localIP
     */
    setLocalIP(localIP) {
        this['localIP'] = localIP;
    }
/**
     * @return {String}
     */
    getMessageID() {
        return this.messageID;
    }

    /**
     * @param {String} messageID
     */
    setMessageID(messageID) {
        this['messageID'] = messageID;
    }
/**
     * @return {String}
     */
    getPreText() {
        return this.preText;
    }

    /**
     * @param {String} preText
     */
    setPreText(preText) {
        this['preText'] = preText;
    }
/**
     * @return {String}
     */
    getPublicIP() {
        return this.publicIP;
    }

    /**
     * @param {String} publicIP
     */
    setPublicIP(publicIP) {
        this['publicIP'] = publicIP;
    }
/**
     * @return {module:sendpost/model/ReplyTo}
     */
    getReplyTo() {
        return this.replyTo;
    }

    /**
     * @param {module:sendpost/model/ReplyTo} replyTo
     */
    setReplyTo(replyTo) {
        this['replyTo'] = replyTo;
    }
/**
     * @return {Number}
     */
    getSubAccountID() {
        return this.subAccountID;
    }

    /**
     * @param {Number} subAccountID
     */
    setSubAccountID(subAccountID) {
        this['subAccountID'] = subAccountID;
    }
/**
     * @return {String}
     */
    getSubject() {
        return this.subject;
    }

    /**
     * @param {String} subject
     */
    setSubject(subject) {
        this['subject'] = subject;
    }
/**
     * @return {Number}
     */
    getSubmittedAt() {
        return this.submittedAt;
    }

    /**
     * @param {Number} submittedAt
     */
    setSubmittedAt(submittedAt) {
        this['submittedAt'] = submittedAt;
    }
/**
     * @return {String}
     */
    getTextBody() {
        return this.textBody;
    }

    /**
     * @param {String} textBody
     */
    setTextBody(textBody) {
        this['textBody'] = textBody;
    }
/**
     * @return {module:sendpost/model/To}
     */
    getTo() {
        return this.to;
    }

    /**
     * @param {module:sendpost/model/To} to
     */
    setTo(to) {
        this['to'] = to;
    }
/**
     * @return {Boolean}
     */
    getTrackClicks() {
        return this.trackClicks;
    }

    /**
     * @param {Boolean} trackClicks
     */
    setTrackClicks(trackClicks) {
        this['trackClicks'] = trackClicks;
    }
/**
     * @return {Boolean}
     */
    getTrackOpens() {
        return this.trackOpens;
    }

    /**
     * @param {Boolean} trackOpens
     */
    setTrackOpens(trackOpens) {
        this['trackOpens'] = trackOpens;
    }

}



/**
 * @member {Number} accountID
 */
QEmailMessage.prototype['accountID'] = undefined;

/**
 * @member {String} ampBody
 */
QEmailMessage.prototype['ampBody'] = undefined;

/**
 * @member {Array.<module:sendpost/model/Attachment>} attachments
 */
QEmailMessage.prototype['attachments'] = undefined;

/**
 * @member {Number} attempt
 */
QEmailMessage.prototype['attempt'] = undefined;

/**
 * @member {Object} customFields
 */
QEmailMessage.prototype['customFields'] = undefined;

/**
 * @member {String} emailType
 */
QEmailMessage.prototype['emailType'] = undefined;

/**
 * @member {module:sendpost/model/From} from
 */
QEmailMessage.prototype['from'] = undefined;

/**
 * @member {Array.<String>} groups
 */
QEmailMessage.prototype['groups'] = undefined;

/**
 * @member {Array.<module:sendpost/model/CopyTo>} headerBcc
 */
QEmailMessage.prototype['headerBcc'] = undefined;

/**
 * @member {Array.<module:sendpost/model/CopyTo>} headerCc
 */
QEmailMessage.prototype['headerCc'] = undefined;

/**
 * @member {module:sendpost/model/To} headerTo
 */
QEmailMessage.prototype['headerTo'] = undefined;

/**
 * @member {Object} headers
 */
QEmailMessage.prototype['headers'] = undefined;

/**
 * @member {String} htmlBody
 */
QEmailMessage.prototype['htmlBody'] = undefined;

/**
 * @member {Number} ipID
 */
QEmailMessage.prototype['ipID'] = undefined;

/**
 * @member {String} ipPool
 */
QEmailMessage.prototype['ipPool'] = undefined;

/**
 * @member {String} localIP
 */
QEmailMessage.prototype['localIP'] = undefined;

/**
 * @member {String} messageID
 */
QEmailMessage.prototype['messageID'] = undefined;

/**
 * @member {String} preText
 */
QEmailMessage.prototype['preText'] = undefined;

/**
 * @member {String} publicIP
 */
QEmailMessage.prototype['publicIP'] = undefined;

/**
 * @member {module:sendpost/model/ReplyTo} replyTo
 */
QEmailMessage.prototype['replyTo'] = undefined;

/**
 * @member {Number} subAccountID
 */
QEmailMessage.prototype['subAccountID'] = undefined;

/**
 * @member {String} subject
 */
QEmailMessage.prototype['subject'] = undefined;

/**
 * @member {Number} submittedAt
 */
QEmailMessage.prototype['submittedAt'] = undefined;

/**
 * @member {String} textBody
 */
QEmailMessage.prototype['textBody'] = undefined;

/**
 * @member {module:sendpost/model/To} to
 */
QEmailMessage.prototype['to'] = undefined;

/**
 * @member {Boolean} trackClicks
 */
QEmailMessage.prototype['trackClicks'] = undefined;

/**
 * @member {Boolean} trackOpens
 */
QEmailMessage.prototype['trackOpens'] = undefined;






export default QEmailMessage;

