/**
 * SendPost API
 * Email API and SMTP relay to not just send and measure email sending, but also alert and optimise. We provide you with tools, expertise and support needed to reliably deliver emails to your customers inboxes on time, every time.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: hello@sendpost.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import SuppressionEmail from './SuppressionEmail';

/**
 * The RDSuppression model module.
 * @module sendpost/model/RDSuppression
 * @version 1.1.1
 */
class RDSuppression {
    /**
     * Constructs a new <code>RDSuppression</code>.
     * @alias module:sendpost/model/RDSuppression
     */
    constructor() { 
        
        RDSuppression.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>RDSuppression</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:sendpost/model/RDSuppression} obj Optional instance to populate.
     * @return {module:sendpost/model/RDSuppression} The populated <code>RDSuppression</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RDSuppression();

            if (data.hasOwnProperty('suppressions')) {
                obj['suppressions'] = ApiClient.convertToType(data['suppressions'], [SuppressionEmail]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>RDSuppression</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>RDSuppression</code>.
     */
    static validateJSON(data) {
        if (data['suppressions']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['suppressions'])) {
                throw new Error("Expected the field `suppressions` to be an array in the JSON data but got " + data['suppressions']);
            }
            // validate the optional field `suppressions` (array)
            for (const item of data['suppressions']) {
                SuppressionEmail.validateJSON(item);
            };
        }

        return true;
    }

/**
     * @return {Array.<module:sendpost/model/SuppressionEmail>}
     */
    getSuppressions() {
        return this.suppressions;
    }

    /**
     * @param {Array.<module:sendpost/model/SuppressionEmail>} suppressions
     */
    setSuppressions(suppressions) {
        this['suppressions'] = suppressions;
    }

}



/**
 * @member {Array.<module:sendpost/model/SuppressionEmail>} suppressions
 */
RDSuppression.prototype['suppressions'] = undefined;






export default RDSuppression;

